version: '3.8'

services:
  playground:
    image: playground:1
    restart: "no"
    volumes:
      - ./ros_ws:/ros_ws
      - ./docker/entryfile.sh:/entryfile.sh
    env_file:
      - .env
    network_mode: host
    privileged: true
    device_cgroup_rules:
      - 'c 81:* rmw'
      - 'c 189:* rmw'